modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="tfd"
version="1.0.0"
displayName="The Five Dimensions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="heath, MCreator"

[[dependencies.tfd]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



